### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by StephanGeorg** [what3words/w3w-node-wrapper#11]
```
npm install w3w-node-wrapper
````
is not available. package.json refers to the old geo.what3words package

**Comment by vicchi** [comment]
That's a stupid mistake and entirely my own fault. I'll fix that either this afternoon or first thing tomorrow morning.

**Comment by vicchi** [comment]
Updated, re-tagged as v2.0.2 and published to NPM (https://www.npmjs.com/package/w3w-node-wrapper)
