### ISSUE TITLE
Package missing from NPM Registry

### ISSUE THREAD

**Issue by tomhut** [what3words/w3w-node-wrapper#32]
It seems this package was removed from (or made private)in the NPM registry earlier today for some reason.
https://www.npmjs.com/package/@what3words/api

If a maintainer could re-add it I would be extremely grateful!

```
npm add @what3words/api
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@what3words%2fapi - Not found
npm ERR! 404 
npm ERR! 404  '@what3words/api@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by c5haw** [comment]
Please try again @tomhut

**Comment by tomhut** [comment]
@c5haw Looks good on my end. Thanks so much and sorry for getting in the way of your Friday night!
